remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
title: Rui Neto - Tech Blog
description: Here, i will write some experiences and tech subjects. CyberSecurity, Systems & Networks.
